	USE ECOMM;
	SELECT * FROM CUSTOMER_CHURN;

					-- Data Cleaning --

/* Handling Missing Values and Outliers */

-- WAREHOUSETOHOME --
	UPDATE CUSTOMER_CHURN
	SET WAREHOUSETOHOME = (
		SELECT ROUND(AVG(WAREHOUSETOHOME)) 
		FROM (SELECT * FROM CUSTOMER_CHURN) AS FILLED 
		)
	WHERE WAREHOUSETOHOME IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE WAREHOUSETOHOME IS NULL;

-- HOURSPENDONAPP --
	UPDATE CUSTOMER_CHURN
	SET HOURSPENDONAPP = (
		SELECT ROUND(AVG(HOURSPENDONAPP)) 
		FROM (SELECT * FROM CUSTOMER_CHURN) AS FILLED 
		)
	WHERE HOURSPENDONAPP IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE HOURSPENDONAPP IS NULL;

-- ORDERAMOUNTHIKEFROMLASTYEAR --
	UPDATE CUSTOMER_CHURN
	SET ORDERAMOUNTHIKEFROMLASTYEAR = (
		SELECT ROUND(AVG(ORDERAMOUNTHIKEFROMLASTYEAR)) 
		FROM (SELECT * FROM CUSTOMER_CHURN) AS FILLED 
		)
	WHERE ORDERAMOUNTHIKEFROMLASTYEAR IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE ORDERAMOUNTHIKEFROMLASTYEAR IS NULL;

-- DAYSINCELASTORDER --
	UPDATE CUSTOMER_CHURN
	SET DAYSINCELASTORDER = (
		SELECT ROUND(AVG(DAYSINCELASTORDER)) 
		FROM (SELECT * FROM CUSTOMER_CHURN) AS FILLED 
		)
	WHERE DAYSINCELASTORDER IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE DAYSINCELASTORDER IS NULL;

-- ==================================================== --

-- TENURE --
	UPDATE CUSTOMER_CHURN
	SET TENURE = (
		SELECT TENURE FROM (SELECT TENURE, COUNT(*)
		FROM CUSTOMER_CHURN
		WHERE TENURE IS NOT NULL
		GROUP BY TENURE 
		ORDER BY COUNT(*) DESC
		LIMIT 1) AS MODE_VALUE)
	WHERE TENURE IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE TENURE IS NULL;
		
-- COUPONUSED --
	UPDATE CUSTOMER_CHURN
	SET COUPONUSED = (
	SELECT COUPONUSED FROM
		(SELECT COUPONUSED, COUNT(*) AS FREQ
		 FROM CUSTOMER_CHURN
		 WHERE COUPONUSED IS NOT NULL
		 GROUP BY COUPONUSED
		 ORDER BY FREQ DESC
		 LIMIT 1 ) AS MODE_VAL)
	WHERE COUPONUSED IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE COUPONUSED IS NULL;

-- ORDERCOUNT --
	UPDATE CUSTOMER_CHURN
	SET ORDERCOUNT = (
	SELECT ORDERCOUNT FROM
		(SELECT ORDERCOUNT, COUNT(*) AS FREQ
		 FROM CUSTOMER_CHURN
		 WHERE ORDERCOUNT IS NOT NULL
		 GROUP BY ORDERCOUNT
		 ORDER BY FREQ DESC
		 LIMIT 1 ) AS MODE_VAL)
	WHERE ORDERCOUNT IS NULL;

	SELECT * FROM CUSTOMER_CHURN
	WHERE ORDERCOUNT IS NULL;

-- ==================================================== --

	DELETE FROM CUSTOMER_CHURN
	WHERE WAREHOUSETOHOME > 100;

# RECHECKING --
	SELECT MAX(WAREHOUSETOHOME) AS HIGHEST_VAL FROM CUSTOMER_CHURN;

	SELECT *  FROM CUSTOMER_CHURN;


/*  Dealing with Inconsistencies */ 

	UPDATE CUSTOMER_CHURN
	SET PREFERREDLOGINDEVICE = 'Mobile Phone'
	WHERE PREFERREDLOGINDEVICE = 'PHONE';

	UPDATE CUSTOMER_CHURN
	SET PREFEREDORDERCAT = 'Mobile Phone'
	WHERE PREFEREDORDERCAT = 'MOBILE'; 

-- ==================================================== --

	UPDATE CUSTOMER_CHURN
	SET PREFERREDPAYMENTMODE = 'Cash on Delivery'
	WHERE PREFERREDPAYMENTMODE = 'COD';

	UPDATE CUSTOMER_CHURN
	SET PREFERREDPAYMENTMODE = 'Credit Card'
	WHERE PREFERREDPAYMENTMODE = 'CC';


				-- Data Transformation --

/* Column Renaming */ 

	ALTER TABLE CUSTOMER_CHURN 
	RENAME COLUMN PreferedOrderCat TO PreferredOrderCat;

	ALTER TABLE CUSTOMER_CHURN
	RENAME COLUMN HourSpendOnApp TO HoursSpentOnApp;

/* Creating New Column */

	ALTER TABLE CUSTOMER_CHURN
	ADD COLUMN ComplaintReceived VARCHAR (4);

	UPDATE CUSTOMER_CHURN
	SET ComplaintReceived = 
	CASE
		WHEN COMPLAIN = 1 THEN  'Yes'
		ELSE 'No'
	END;
    
-- ==================================================== --

	ALTER TABLE CUSTOMER_CHURN
	ADD COLUMN ChurnStatus VARCHAR (10);

	UPDATE CUSTOMER_CHURN
	SET ChurnStatus = 
	CASE
		WHEN CHURN = 1 THEN 'Churned'
		ELSE 'Active'
	END;

/*Column Dropping*/

	ALTER TABLE CUSTOMER_CHURN
	DROP COLUMN CHURN,
	DROP COLUMN COMPLAIN;

			-- Data Exploration and Analysis --
            
SELECT *  FROM CUSTOMER_CHURN;

-- 01 ----    
	SELECT CHURNSTATUS,
		COUNT(*) AS TOT_COUNT
	FROM CUSTOMER_CHURN
		GROUP BY CHURNSTATUS;
    
-- 02 --
	SELECT CHURNSTATUS, 
		ROUND(AVG(TENURE),2) AS AVG_TENURE,
		ROUND(SUM(CASHBACKAMOUNT),2) AS TOT_CASH_BACK
	FROM CUSTOMER_CHURN
		WHERE CHURNSTATUS = 'CHURNED';
		
-- 03 --
	SELECT 	
		COUNT( CASE
			WHEN ComplaintReceived = 'Yes' THEN 1 END)* 100 / COUNT(*) AS TOT_PERCENTAGE
	FROM CUSTOMER_CHURN
		WHERE CHURNSTATUS = 'CHURNED';
    
-- 04 --    
	SELECT CITYTIER,
		COUNT(*) AS CHURNED_COUNT
	FROM CUSTOMER_CHURN
		WHERE CHURNSTATUS = 'CHURNED'
		AND PREFERREDORDERCAT = 'Laptop & Accessory'
	GROUP BY CITYTIER
	ORDER BY CHURNED_COUNT DESC
	LIMIT 1;

-- 05 --
	SELECT PREFERREDPAYMENTMODE, 
		COUNT(*) AS TOT_COUNT
	FROM CUSTOMER_CHURN
		WHERE CHURNSTATUS = 'ACTIVE'
	GROUP BY PREFERREDPAYMENTMODE
	ORDER BY TOT_COUNT DESC
	LIMIT 1;

-- 06 --
	SELECT ROUND(SUM(ORDERAMOUNTHIKEFROMLASTYEAR),2) AS TOTAL_ORDER_HIKE
	FROM CUSTOMER_CHURN
		WHERE MARITALSTATUS = 'SINGLE'
		AND PREFERREDORDERCAT = 'MOBILE PHONE';
		
-- 07 --
	SELECT ROUND(AVG(NUMBEROFDEVICEREGISTERED),2) AS AVG_DEVICE
	FROM CUSTOMER_CHURN
		WHERE PREFERREDPAYMENTMODE = 'UPI';
		
-- 08 --
	SELECT CITYTIER, 
		COUNT(*) AS TOT_CUTOMER_COUNT
	FROM CUSTOMER_CHURN
	GROUP BY CITYTIER
	ORDER BY  TOT_CUTOMER_COUNT DESC
	LIMIT 1;

-- 09 -- 
	SELECT GENDER, 
		SUM(COUPONUSED) AS TOT_COUPON
	FROM CUSTOMER_CHURN
	GROUP BY GENDER
	ORDER BY TOT_COUPON DESC
	LIMIT 1;

-- 10 --
	SELECT PREFERREDORDERCAT,
		MAX(HOURSSPENTONAPP) AS MAX_HOURS_ON_APP,
		COUNT(*) AS CUSTOMER_COUNT
	FROM CUSTOMER_CHURN
	GROUP BY PREFERREDORDERCAT
	ORDER BY CUSTOMER_COUNT;

-- 11 --
	SELECT SUM(ORDERCOUNT) AS TOT_ORDER
	FROM CUSTOMER_CHURN
		WHERE PREFERREDPAYMENTMODE = 'CREDIT CARD'
		AND SATISFACTIONSCORE = (
			SELECT MAX(SATISFACTIONSCORE)
			FROM CUSTOMER_CHURN
		);
			
-- 12 --
	SELECT ROUND(AVG(SATISFACTIONSCORE),2) AS AVG_SATISFACTION
	FROM CUSTOMER_CHURN
		WHERE COMPLAINTRECEIVED = 'YES';
		
-- 13 --
	SELECT PREFERREDORDERCAT,
		COUNT(*) AS TOT_COUNT
	FROM CUSTOMER_CHURN
		WHERE COUPONUSED >5
	GROUP BY PREFERREDORDERCAT
	ORDER BY TOT_COUNT DESC;

-- 14 --
	SELECT PREFERREDORDERCAT,
		ROUND(AVG(CASHBACKAMOUNT),2) AS AVG_CASHBACK
	FROM CUSTOMER_CHURN
	GROUP BY PREFERREDORDERCAT
	ORDER BY AVG_CASHBACK DESC
	LIMIT 3;
		
-- 15 --
	SELECT PREFERREDPAYMENTMODE,
		ROUND(AVG(TENURE),2) AS AVG_TENURE,
		SUM(ORDERCOUNT) AS TOT_ORDER
	FROM CUSTOMER_CHURN
	GROUP BY PREFERREDPAYMENTMODE
		HAVING ROUND(AVG(TENURE)) = 10
		AND SUM(ORDERCOUNT) > 500; 
		
-- 16 --
	SELECT CHURNSTATUS,
		CASE
		WHEN WAREHOUSETOHOME <=5 THEN 'Very Close Distance'
		WHEN WAREHOUSETOHOME <=10 THEN  'Close Distance'
		WHEN WAREHOUSETOHOME <=15 THEN  'Moderate Distance'
		ELSE 'Far Distance'
	END AS DISTENCE_CAT,
		COUNT(*) AS TOT_COUNT
	FROM CUSTOMER_CHURN
	GROUP BY DISTENCE_CAT,CHURNSTATUS
	ORDER BY DISTENCE_CAT,CHURNSTATUS;

-- 17 --
	SELECT CUSTOMERID,
		MARITALSTATUS,
		CITYTIER,
		ORDERCOUNT,
		PREFERREDORDERCAT,
		PREFERREDPAYMENTMODE
	FROM CUSTOMER_CHURN
		WHERE MARITALSTATUS = 'MARRIED'
		AND CITYTIER = 1
		AND ORDERCOUNT>(
			SELECT ROUND(AVG(ORDERCOUNT),2) 
			FROM CUSTOMER_CHURN
			)
	ORDER BY ORDERCOUNT DESC;


-- 18 -- 
	-- (A) --
	CREATE TABLE CUSTOMER_RETURNS (
		ReturnID INT PRIMARY KEY,
		CustomerID INT,
		ReturnDate 	DATE,
		RefundAmount DECIMAL (10,2)
	);

	INSERT INTO CUSTOMER_RETURNS VALUES
		(1001, 50022, '2023-01-01', 2130),
		(1002, 50316, '2023-01-23', 2000),
		(1003, 51099, '2023-02-14', 2290),
		(1004, 52321, '2023-03-08', 2510),
		(1005, 52928, '2023-03-20', 3000),
		(1006, 53749, '2023-04-17', 1740),
		(1007, 54206, '2023-04-21', 3250),
		(1008, 54838, '2023-04-30', 1990);

	SELECT * FROM CUSTOMER_RETURNS;

	-- (B) --
    
	SELECT 
		CR.RETURNID,
		CR.CUSTOMERID,
		CR.RETURNDATE,
		CR.REFUNDAMOUNT,
		CC.CHURNSTATUS,
		CC.COMPLAINTRECEIVED,
		CC.PREFERREDPAYMENTMODE,
		CC.CITYTIER
	FROM CUSTOMER_RETURNS CR 
		INNER JOIN CUSTOMER_CHURN CC
		ON CR.CUSTOMERID = CC.CUSTOMERID
		WHERE CC.CHURNSTATUS = 'CHURNED'
		AND CC.COMPLAINTRECEIVED = 'YES'
	ORDER BY CR.ReturnDate
